config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get "welcome/index"
  resources :newspapers
  resources :jobs
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/newspaper.rb
require 'open-uri'

class Newspaper < ApplicationRecord
  has_many :articles
  after_update do
     p "hey"
     doc = Nokogiri::HTML(URI.open(self.link))
     p doc.css('.title').text
     p doc.css('.entry-content').text
     p doc.css('.post-meta-bar-author').text
  end
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  before_action :set_newspaper, only: %i[ show edit update destroy ]

  # GET /newspapers or /newspapers.json
  def index
    @newspapers = Newspaper.all
  end

  # GET /newspapers/1 or /newspapers/1.json
  def show
  end

  # GET /newspapers/new
  def new
    @newspaper = Newspaper.new
  end

  # GET /newspapers/1/edit
  def edit
  end

  # POST /newspapers or /newspapers.json
  def create
    @newspaper = Newspaper.new(newspaper_params)

    respond_to do |format|
      if @newspaper.save
        format.html { redirect_to @newspaper, notice: "Newspaper was successfully created." }
        format.json { render :show, status: :created, location: @newspaper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newspapers/1 or /newspapers/1.json
  def update
    respond_to do |format|
      if @newspaper.update(newspaper_params)
        format.html { redirect_to @newspaper, notice: "Newspaper was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @newspaper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newspapers/1 or /newspapers/1.json
  def destroy
    @newspaper.destroy!

    respond_to do |format|
      format.html { redirect_to newspapers_path, notice: "Newspaper was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newspaper
      @newspaper = Newspaper.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def newspaper_params
      params.expect(newspaper: [ :name, :link, :myinfo, :title, :content, :author ])
    end
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/views/newspapers/_form.html.erb
<%= form_with(model: newspaper) do |form| %>
  <% if newspaper.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(newspaper.errors.count, "error") %> prohibited this newspaper from being saved:</h2>

      <ul>
        <% newspaper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :link, "lien d'1 article", style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :myinfo, style: "display: block" %>
    <%= form.text_field :myinfo %>
  </div>
  <div>
    <%= form.label :title, "class name/id name for title", style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content, "classname for content", style: "display: block" %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.label :author, "classname /id for name of author", style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/newspapers/_newspaper.html.erb
<div id="<%= dom_id newspaper %>">
  <p>
    <strong>Name:</strong>
    <%= newspaper.name %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= newspaper.link %>
  </p>

  <p>
    <strong>Info:</strong>
    <%= newspaper.myinfo %>
  </p>

</div>

app/views/newspapers/edit.html.erb
<% content_for :title, "Editing newspaper" %>

<h1>Editing newspaper</h1>

<%= render "form", newspaper: @newspaper %>

<br>

<div>
  <%= link_to "Show this newspaper", @newspaper %> |
  <%= link_to "Back to newspapers", newspapers_path %>
</div>

app/views/newspapers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Newspapers" %>

<h1>Newspapers</h1>

<div id="newspapers">
  <% @newspapers.each do |newspaper| %>
    <%= render newspaper %>
    <p>
      <%= link_to "Show this newspaper", newspaper %>
    </p>
  <% end %>
</div>

<%= link_to "New newspaper", new_newspaper_path %>

app/views/newspapers/new.html.erb
<% content_for :title, "New newspaper" %>

<h1>New newspaper</h1>

<%= render "form", newspaper: @newspaper %>

<br>

<div>
  <%= link_to "Back to newspapers", newspapers_path %>
</div>

app/views/newspapers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @newspaper %>
<h3>ajouter un autre article </h3>
<%= render "articles/form", article: Article.new(newspaper_id: @newspaper.id) %>
<div style="float: left;clear: both;" class="row row-cols-1 row-cols-md-2 g-4">
<%@newspaper.articles.each do |n|%>
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%=link_to n.title, n%></h5>
        <p class="card-text"><%= n.content.truncate(100)%></p>
        <p class="card-text"><%=n.author%></p>
      </div>
    </div>
  </div>
<%end%>
</div>


<div style="float:left;clear:both;">

  <%= link_to "Edit this newspaper", edit_newspaper_path(@newspaper) %> |
  <%= link_to "Back to newspapers", newspapers_path %>

  <%= button_to "Destroy this newspaper", @newspaper, method: :delete %>
</div>